# Generated By ChatGPT

import os
import subprocess
import glob
import shutil
from pathlib import Path

OUTPUT_DIRECTORY = "./assets/shader"
TARGET_DIRECTORY = "./src/shader/hlsl"
GLSL_SOURCE_DIRECTORY = "./src/shader/glsl"
VERTEX_SHADER_FILE_PREFIX = "vs_"
PIXEL_SHADER_FILE_PREFIX = "ps_"
COMPUTE_SHADER_FILE_PREFIX = "cs_"
EXTENSION = ".dxbc"


def get_fxc_path():
    """
    Windows SDKのディレクトリから最新の fxc.exe のパスを取得する
    """
    base_sdk_path = Path(r"C:\Program Files (x86)\Windows Kits\10\bin")

    if not base_sdk_path.exists():
        return None

    # 10.0.XXXXX.0 形式のディレクトリを取得して降順（最新順）にソート
    version_dirs = sorted(
        [
            d
            for d in base_sdk_path.iterdir()
            if d.is_dir() and d.name.startswith("10.0.")
        ],
        reverse=True,
    )

    for v_dir in version_dirs:
        fxc_path = v_dir / "x64" / "fxc.exe"
        if fxc_path.exists():
            return str(fxc_path)

    return None


def compile_hlsl_files(input_dir: str, output_root: str):
    """
    input_dir内のHLSLを探索し、output_rootにディレクトリ構造を維持してコンパイル後のバイナリを出力する
    """
    compiler = get_fxc_path()
    if not compiler:
        print("Error: fxc.exe が見つかりません。")
        return

    # 再帰的に全.hlslファイルを取得
    search_pattern = os.path.join(input_dir, "**/*.hlsl")
    hlsl_files = glob.glob(search_pattern, recursive=True)

    for filepath in hlsl_files:
        filename = os.path.basename(filepath)

        # 1. 入力ルートからの相対パスを取得 (例: "subfolder/vs_test.hlsl")
        rel_path = os.path.relpath(filepath, input_dir)

        # 2. 出力先のパスを組み立て、拡張子を変更
        dest_path = os.path.join(
            output_root, os.path.splitext(rel_path)[0] + EXTENSION
        )

        # 3. 出力先ディレクトリが存在しない場合は作成
        os.makedirs(os.path.dirname(dest_path), exist_ok=True)

        # プレフィックス判定
        if filename.startswith(VERTEX_SHADER_FILE_PREFIX):
            profile, entry_point = "vs_5_0", "main"
        elif filename.startswith(PIXEL_SHADER_FILE_PREFIX):
            profile, entry_point = "ps_5_0", "main"
        elif filename.startswith(COMPUTE_SHADER_FILE_PREFIX):
            profile, entry_point = "cs_5_0", "main"
        else:
            continue

        # コンパイル実行
        command = [
            compiler,
            "/T",
            profile,
            "/E",
            entry_point,
            "/Fo",
            dest_path,
            filepath
        ]

        try:
            print(
                f"Compiling: {rel_path} -> {os.path.relpath(dest_path, output_root)}"
            )
            subprocess.run(command, capture_output=True, text=True, check=True)
        except subprocess.CalledProcessError as e:
            print(f"Failed to compile {filename}:\n{e.stderr}")


def copy_glsl_files(input_dir: str, output_root: str):
    search_pattern = os.path.join(input_dir, "**/*.glsl")
    for filepath in glob.glob(search_pattern, recursive=True):
        rel_path = os.path.relpath(filepath, input_dir)
        dest_path = os.path.join(output_root, rel_path)
        os.makedirs(os.path.dirname(dest_path), exist_ok=True)
        print(f"Copying: {rel_path} -> {os.path.relpath(dest_path, output_root)}")
        shutil.copy2(filepath, dest_path)


if __name__ == "__main__":
    compile_hlsl_files(TARGET_DIRECTORY, OUTPUT_DIRECTORY)
    copy_glsl_files(GLSL_SOURCE_DIRECTORY, OUTPUT_DIRECTORY)
