name: Windows MSBuild

on:
  push:
  pull_request:

# cmakeビルド環境が整うまでMSBuildを使用
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        config: [Release, Debug]
        #platform: [x86, x64]
        platform: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Developer Command
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.platform }}

      - name: Cache CMake build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: build
          key: cmake-build-${{ matrix.platform }}-${{ hashFiles('build.cmd', '**/CMakeLists.txt') }}

      - name: Run build.cmd (generate lib with CMake)
        if: steps.cache-build.outputs.cache-hit != 'true'
        run: |
          build.cmd
        shell: cmd

      - name: MSBuild
        run: |
          msbuild DesktopCharacter.sln ^
            /p:Configuration=${{ matrix.config }} ^
            /p:Platform=${{ matrix.platform }} ^
            /m
        shell: cmd