name: Windows CMake

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-2022

    strategy:
      matrix:
        config: [Release, Debug]
        #platform: [x86, x64]
        platform: [x64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          
      - name: Setup Developer Command
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.platform }}

      - name: Cache CMake dependencies
        uses: actions/cache@v4
        with:
          path: |
            build/_deps
            build/libs
          key: ${{ runner.os }}-cmake-${{ matrix.platform }}-${{ matrix.config }}-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-cmake-${{ matrix.platform }}-${{ matrix.config }}-

      - name: Configure
        run: |
          cmake -S src -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.config }}
        shell: cmd

      - name: Build
        run: |
          cmake --build build --parallel
        shell: cmd